services:
  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"