version: '3'

networks:
  main_network:
    driver: bridge

services:
  postgres:
    container_name: "postgres"
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "medialibrary"
    restart: on-failure
    networks:
      - main_network
  go:
    container_name: "go"
    build:
      context: .
      dockerfile: ./docker/go_test.Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./coverage:/app/coverage
    networks:
      - main_network