services:
  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  go:
    build:
      context: .
      dockerfile: ./docker/go.Dockerfile
    links:
      - "db:postgres"
    ports:
      - "8080:8080"