server:
  port: :8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: medialibrary
  maxidleconnections: 5
  maxopenconnections: 10
  maxconnidletime: 60s