server:
  port: :8080

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: medialibrary
  maxidleconnections: 5
  maxopenconnections: 10
  maxconnidletime: 60s

database_test:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: medialibrary_test
  maxidleconnections: 5
  maxopenconnections: 10
  maxconnidletime: 60s

